-- This file documents the SQL analysis flow
-- 
-- 01_base_sales.sql:
--   Base data selection and standardisation
--
-- 02_monthly_growth.sql:
--   Monthly aggregation and MoM growth analysis
--
-- 03_product_performance.sql:
--   Product-level revenue performance
--
-- Each script can be run independently to explore a specific
-- analytical aspect of sales performance.
``
